obj-$(CPTCFG_6LOWPAN) += 6lowpan.o

6lowpan-y := iphc.o nhc.o

#rfc6282 nhcs
obj-$(CPTCFG_6LOWPAN_NHC_DEST) += nhc_dest.o
obj-$(CPTCFG_6LOWPAN_NHC_FRAGMENT) += nhc_fragment.o
obj-$(CPTCFG_6LOWPAN_NHC_HOP) += nhc_hop.o
obj-$(CPTCFG_6LOWPAN_NHC_IPV6) += nhc_ipv6.o
obj-$(CPTCFG_6LOWPAN_NHC_MOBILITY) += nhc_mobility.o
obj-$(CPTCFG_6LOWPAN_NHC_ROUTING) += nhc_routing.o
obj-$(CPTCFG_6LOWPAN_NHC_UDP) += nhc_udp.o
